[tool]
name = "general_utilities"
version = "1.2.0"
description = ""
authors = ["Eugene Gardner <eugene.gardner@mrc-epid.cam.ac.uk>"]
readme = "README.md"
repository = "https://github.com/mrcepid-rap/general_utilities"
licence = "MIT"

[dependencies]
