from typing import Iterator

from general_utilities.job_management.job_launcher_interface import JobLauncherInterface
from general_utilities.job_management.subjob_utility import SubjobUtility
from general_utilities.job_management.thread_utility import ThreadUtility
from general_utilities.mrc_logger import MRCLogger
from general_utilities.platform_utils.platform_factory import Platform, PlatformFactory


class JobLauncher(JobLauncherInterface):
    """
    Job launcher that uses either SubjobUtility for DX or ThreadUtility for local execution.
    GCP is not supported in this implementation.

    This class detects the platform and initializes the appropriate backend utility for job management.
    It provides methods to launch jobs, submit and monitor them, and retrieve outputs.

    :param incrementor: The incrementor for job submission, default is 500.
    :param threads: The number of threads to use for local execution, default is None.
    :raises NotImplementedError: If GCP platform is detected.
    :raises RuntimeError: If an unsupported platform is detected.
    """

    def __init__(self, **kwargs):
        self._logger = MRCLogger(__name__).get_logger()

        self._platform = PlatformFactory().get_platform()
        self._logger.info(f"Detected platform: {self._platform.value}")

        super().__init__(incrementor=kwargs.get('incrementor', 500),
                         threads=kwargs.get('threads'))

        if self._platform == Platform.DX:
            self._backend = SubjobUtility(**kwargs)
        elif self._platform == Platform.LOCAL:
            self._backend = ThreadUtility(**kwargs)
        elif self._platform == Platform.GCP:
            raise NotImplementedError("GCP platform is not supported in this implementation.")
        else:
            raise RuntimeError("Unsupported platform, please seek help")

    def launch_job(self, function, inputs, outputs=None, name=None, instance_type=None) -> None:
        """
        Queue a subjob with the given parameters.
        :param function: The function to execute as a subjob.
        :param inputs: A dictionary of input parameters for the job.
        :param outputs: A list of output files to be generated by the job (optional).
        :param name: The name of the job (optional).
        :param instance_type: The type of instance to use for the job (optional).
        :return: None
        """
        if self._platform == Platform.DX:
            self._backend.launch_job(function=function, inputs=inputs, outputs=outputs,
                                     name=name, instance_type=instance_type)
        elif self._platform == Platform.LOCAL:
            self._backend.launch_job(function=function, **inputs)

    def submit_and_monitor(self) -> None:
        """
        Submit the queued jobs and monitor their execution.
        :return: None
        """
        self._backend.submit_and_monitor()

    def get_outputs(self) -> Iterator:
        """
        Retrieve outputs of completed jobs.
        :return: An iterator over the outputs from the subjobs.
        """
        return iter(self._backend)

    @property
    def platform(self) -> Platform:
        """
        Return the detected platform for this job launcher.
        :return: The platform to run the subjobs on.
        """
        return self._platform
